vim.keymap.set("n", "<leader>fd", vim.cmd.Ex)
vim.keymap.set({ "n", "x" }, "cp", '"+y')
vim.keymap.set({ "n", "x" }, "cv", '"+p')
vim.keymap.set({ "n", "x" }, "<leader>bn", ":bNext<enter>")
vim.keymap.set({ "n", "x" }, "<leader>bp", ":bprevious<enter>")

vim.keymap.set("t", "<C-W>", "<C-\\><C-n>")

local dap = require("dap")
vim.keymap.set("n", "<F5>", function() dap.continue() end)
vim.keymap.set("n", "<F10>", function() dap.step_over() end)
vim.keymap.set("n", "<F11>", function() dap.step_into() end)
vim.keymap.set("n", "<F12>", function() dap.step_out() end)

vim.keymap.set("n", "<leader>dc", function() dap.continue() end)
vim.keymap.set("n", "<leader>dl", function() dap.step_over() end)
vim.keymap.set("n", "<leader>dj", function() dap.step_into() end)
vim.keymap.set("n", "<leader>dk", function() dap.step_out() end)
vim.keymap.set("n", "<Leader>db", function() dap.toggle_breakpoint() end)
vim.keymap.set("n", "<Leader>dB", function() dap.set_breakpoint() end)
vim.keymap.set("n", "<Leader>dlp", function() dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: ")) end)
vim.keymap.set("n", "<Leader>de", function() dap.repl.open() end)
vim.keymap.set("n", "<Leader>dr", function() dap.run_last() end)

vim.keymap.set({ "n", "v" }, "<Leader>dh", function() require("dap.ui.widgets").hover() end)
vim.keymap.set({ "n", "v" }, "<Leader>dp", function() require("dap.ui.widgets").preview() end)
vim.keymap.set("n", "<Leader>df", function()
    local widgets = require("dap.ui.widgets")
    widgets.centered_float(widgets.frames)
end)
vim.keymap.set("n", "<Leader>ds", function()
    local widgets = require("dap.ui.widgets")
    widgets.centered_float(widgets.scopes)
end)
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = "Open diagnostics list" })
vim.keymap.set('n', "<leader>st", ":SymbolsOutline<enter>")
